### ISSUE TITLE
Performance/ Code touch-up

### ISSUE THREAD

**Issue by mjrouser** [codeforboston/ungentry#27]
Our code is pretty hacked together, and it shows in the site performance.  Suggestions/pull requests that will help clean things up or boost our performance are very welcome.

We also need someone to take a look at the JS and see if integrating a framework like [knockoutJS] (http://knockoutjs.com/), or something bigger like [Durandal] (http://durandaljs.com/) or [Backbone] (http://backbonejs.org/) would be helpful.

**Comment by bendman** [comment]
@mjrouser No... I'm in DC all week for work. Someone else is welcome to start on this, as I'll be pretty busy in the coming weeks. I didn't get very far on the cleanup before leaving, so there's not much lost work.

**Comment by thecristen** [comment]
Hey, I've been learning a lot of Backbone for work, so I can probably help out on this! We should definitely identify our needs, figure out what sort of structures we have in mind, etc...

**Comment by mjrouser** [comment]
That's great Christen!  We started that conversation on Tuesday a bit.  Perhaps you can help guide that process as we go forward?
