### ISSUE TITLE
Bootstrap responsive design makes it so you can't scroll off the map on cellphones

### ISSUE THREAD

**Issue by powpow12** [codeforboston/ungentry#30]
Because of the responsive nature of bootstrap, small screens will focus directly on the map.  When a user tries to scroll away from the map they interact with it.

**Comment by mjrouser** [comment]
This issue has come a long way Thanks to @powpow12!  

There is a small bug that still needs to be squashed:  

When the browser is shrunk, and the tabs become visible, if you navigate to the "2000" or "2010" tabs, and resize the browser larger, the other two maps remain 'hidden.'  

The following snippets need to be edited:
This snippet of HTML: 

<ul class="nav nav-tabs" id="small_display">
  <li role="presentation" id='link_1990'><a href="">1990</a></li>
  <li role="presentation" id='link_2000'><a href="">2000</a></li>
  <li role="presentation" id='link_2010'><a href="">2010</a></li>
</ul> 

 <div class="row maps"> 
  <div id="map0" class="map col-xs-12 col-md-4">
   	<h2 id="date">1990</h2>
  </div>
  <div id="map1" class="map col-xs-12 col-md-4 toHide">
   	<h2>2000</h2>
  </div>
  <div id="map2" class="map col-xs-12 col-md-4 toHide">
   	<h2>2010</h2>
  </div>
 </div>

And this snippet of JS:

function removeMaps(){

	if (datamap0) datamap0.remove();
	if (datamap1) datamap1.remove();
	if (datamap2) datamap2.remove();

	delete datamap0;
	delete datamap1;
	delete datamap2;

	datamap0 = null;
	datamap1 = null;
	datamap2 = null;

}

**Comment by mjrouser** [comment]
This issue has come a long way Thanks to @powpow12!  

There is a small bug that still needs to be squashed:  

When the browser is shrunk, and the tabs become visible, if you navigate to the "2000" or "2010" tabs, and resize the browser larger, the other two maps remain 'hidden.'  

The following snippets need to be edited:
This snippet of HTML
 ```HTML 

<ul class="nav nav-tabs" id="small_display">
  <li role="presentation" id='link_1990'><a href="">1990</a></li>
  <li role="presentation" id='link_2000'><a href="">2000</a></li>
  <li role="presentation" id='link_2010'><a href="">2010</a></li>
</ul> 

 <div class="row maps"> 
  <div id="map0" class="map col-xs-12 col-md-4">
   	<h2 id="date">1990</h2>
  </div>
  <div id="map1" class="map col-xs-12 col-md-4 toHide">
   	<h2>2000</h2>
  </div>
  <div id="map2" class="map col-xs-12 col-md-4 toHide">
   	<h2>2010</h2>
  </div>
 </div>
```
And this snippet of JS

```javascript

function removeMaps(){

	if (datamap0) datamap0.remove();
	if (datamap1) datamap1.remove();
	if (datamap2) datamap2.remove();

	delete datamap0;
	delete datamap1;
	delete datamap2;

	datamap0 = null;
	datamap1 = null;
	datamap2 = null;

}
```

**Comment by powpow12** [comment]
I checked this out via my galaxy s3, looks like there is a render issue with map2 and 3...

**Comment by mjrouser** [comment]
You are correct.  I'm reopening with two bugs:

1. In small screen mode, `#map1` and `#map2` are not displaying fully across the div

2. The breakpoint for `col-xs- ` is currently 990px.  According to the Bootstrap docs, it should be a more sensible 768px.  We need to find the conflict in the code.
