### ISSUE TITLE
RequireJS implementation

### ISSUE THREAD

**Issue by mjrouser** [codeforboston/ungentry#41]
As a pre-req, to implementing an MVC, it will be helpful to have an AMD. RequireJS has good documentation and is lightweight.

**Comment by mjrouser** [comment]
@isaacchansky, Julien has committed his changes to the repo, so if you could go ahead and bring in the require stuff, that would be amazing.

**Comment by isaacchansky** [comment]
nice! I'll see what I can get done tonight.

**Comment by isaacchansky** [comment]
Something that might be nice to do in conjunction with the move to requireJS, is to move to a dependency management system like [Bower](http://bower.io/) . Thoughts?

**Comment by mjrouser** [comment]
It's a good idea, but I think it might be overkill at this point.  Once we get closer to publishing a production version we should revisit it.  I'll add an issue in the mean time.
