### ISSUE TITLE
Dependency Management/ Minification for production version

### ISSUE THREAD

**Issue by mjrouser** [codeforboston/ungentry#47]
After we have all features authored, and the modules switched over to backbone formatting, we'll be ready to release a production version.  At this point we need to look into tools such as [Bower](http://bower.io)  and [Grunt](http://gruntjs.com).

**Comment by isaacchansky** [comment]
On a related note, I think that having a (more) complex build using grunt/bower/etc does not necessarily mean abandoning the fork & go methodology, just changing it.

I'm of course not sure of your thoughts on this but I know with finda there was some concern over adding a build process as that does mean that the version with a build process is not gh-pages/fork&go compatible.   

It is possible, though, to have both a "build" and a "built" version, with the master branch having your regular webapp project with a build process employed and the traditional `src` and `dist` directories, and then after every big update we can just build and push the `dist` folder to a gh-pages branch. 

here's a nice gist of how we could do that. 
https://gist.github.com/cobyism/4730490

Perhaps you've already thought all this through but I just wanted to drop it in this issue for reference :)

**Comment by mjrouser** [comment]
Thanks for pulling all those thoughts together in such a clear way Isaac!  I agree with you overall and this is more or less the kind of process I had in mind as well.  I just figured we would wait until we are closer to an actual 1.0 release.  

The fork & go issue is not as pressing for us as Finda, as it's our data and results that we want to spread, and not necessarily other instances of the app.  However, I do want to make our development version as accessible as possible for people to get involved with, and adding build steps is a little higher-level IMHO.

Have any other thoughts?  Otherwise, lets revisit when we get closer to release.
