### ISSUE TITLE
relocate legend

### ISSUE THREAD

**Issue by mjrouser** [codeforboston/ungentry#49]
We want to take the legend out of the map div and relocate it to the sidebar.  This way we will not have three instances of the legend, and can free up map space.  

Step 1.: Break out the code from prospect/censuslayer/js/CensusLayer.js and create a require module in the src folder.

``` javascript
			_loadLegend : function() {

				if (this._legend) {
					this._map.removeControl(this._legend);
				}

				var self = this;
				this._legend = L.control({position: 'bottomright'});
				this._legend.onAdd = function (lwrapper) {
					debugger;
					var div = L.DomUtil.create('div', 'info legend');
					if (self._currentProperty!="") {

						var prop = self._properties_data[self._currentProperty];

						if (prop) {
							var geo = prop.serie;


							div.innerHTML += '<h4>'+prop.title+'</h4>';
							for (var i = 0; i < 5; i++) {
							    var range_min = geo[i].toFixed(0);
							    var range_max =  geo[i+1].toFixed(0);
							    var color =  self._getColor(geo, (parseFloat(range_max)+parseFloat(range_min))/2 );
							    div.innerHTML += '<i style="background: ' + color + ';"></i> ' + range_min + prop.unit + " - " + range_max + prop.unit + '<br>';
							}
						}


					}
					lwrapper.html(div);
					//return div;
			    	};
				this._legend.addTo($('.lwrapper'));

```

Step 2.: hack the `addTo()` method to attach the legend to `div.lwrapper`.

**Comment by mjrouser** [comment]
I broke out the legend code to its own module, and migrated all work on the new homepage to the `new-home` branch. 

Separating this code from the rest of the census layer file also separated it from the required data.  Soooo, each section needs to be broken out into a module, and worked into require. 

Step 2 is still untouched....

**Comment by mjrouser** [comment]
@isaacchansky, have you had a chance to look at this this week?  :-)

**Comment by isaacchansky** [comment]
indeed! #63
