### ISSUE TITLE
2010 %Unit Ownership Rates are below Census values in the MBDC

### ISSUE THREAD

**Issue by radumas** [codeforboston/ungentry#55]
Assuming this is referring to the percentage of occupied housing that is occupied by the owner, and the ungentry data source is the census, then the values in ungentry do not appear to match census data in the data common.  See the comparable map here http://metrobostondatacommon.org/visualizations/2869/ . The data for that map aggregated by municipality (the census tract data seems to be broken on MBDC) but the source is the Census.

You can see that cities such as Weston, which had 85% owner-occupancy according to the Census, shows as having <38% owner-occupancy on ungentry.

Zooming out to the whole metro, as the image below shows, would show that owner-occupancy fell by 38%-79% from 2000-2010
![ungentry_owneroccupied](https://cloud.githubusercontent.com/assets/10623872/6476362/d6e6a53a-c1e2-11e4-89ee-2f432b910c45.png)

**Comment by jacks1177** [comment]
Found an error in the denominator for the code for 2010. Fixed this.

**Comment by radumas** [comment]
Not knowing where in the code this appears, just making sure you caught that the problem also seems to affect % units rented.
Thanks!

**Comment by mjrouser** [comment]
@bouviervj did you push the new data to `new-home` as well as `gh-pages`?
