### ISSUE TITLE
Create custom tiles via Mapbox

### ISSUE THREAD

**Issue by mjrouser** [codeforboston/ungentry#57]
Our current tiles have some extraneous label information.  If Mapbox allows, it would be ideal to pare labeling down to city, neighborhood and major/semi-major roadways.  This would hopefully be better for people looking to orient their perspective on the map view, and orient the map away from way finding.

Ideally, we would keep the aesthetic of the "Toner" tiles that we have currently via Stamen.

**Comment by mjrouser** [comment]
This is going to be a big task, so for now, a good step would be to combine the new positron basemap from CartoDB/Stamen: http://cartodb.com/basemaps/     and issue #52.

**Comment by bouviervj** [comment]
Hi Matt,

I'm currently developing a server that can serve tiles among Census Data, I
can show you this work tonight.
I would like to push this work in a github repository.
I have seen that our json approach is interesting because it requires few
mb of data hosted on github project.

Cheers,
Julien
