### ISSUE TITLE
Create Info Window

### ISSUE THREAD

**Issue by mjrouser** [codeforboston/ungentry#60]
This work is taking place in the `new-home` branch.

Underneath the nav tabs for data variables, the `iwindow` div needs to be populated with data from the map according to which census tract is moused over. 

2. City>Neighborhood>Census Tract ID
3. The value of the selected variable for that census tract

This will have similar requirements to issue #49 in terms of exporting data from the map div to display elsewhere.

**Comment by brisandbeans** [comment]
Is it all right if I work on this?

**Comment by mjrouser** [comment]
Absolutely!

On Tuesday, May 12, 2015, brisandbeans <notifications@github.com> wrote:

> Is it all right if I work on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforboston/ungentry/issues/60#issuecomment-101494145>
> .
>


-- 
--
http://mjrouser.com

Sent using a tiny keyboard.

**Comment by mjrouser** [comment]
This issue is very close to being buttoned up.  The last thing I want to include is the value symbol (eg. '%' or '$') with the values on rollover. 

I would also like some input on the addition of the color behind the census tract values on rollover.

**Comment by mjrouser** [comment]
Done and done.  Thanks so much @brisandbeans!!
