### ISSUE TITLE
Average rents vs median income

### ISSUE THREAD

**Issue by powpow12** [codeforboston/ungentry#66]
comment off of http://goo.gl/0XVxMc
There's got to be something wrong with using "average" rents but "median" incomes together, but I'm not a statistician. Then again, these "volunteers" probably aren't, either.

**Comment by jacks1177** [comment]
I don't think we're using average rents unless the data is coming from a different source. The main dataset are medians. The site is incorrectly labeled.

**Comment by mjrouser** [comment]
Thanks @jacks1177!!!  @bouviervj do you know how to show the correct title on our legend?

**Comment by bouviervj** [comment]
Yes, I will correct it today @ the hack. Probably we will need to introduce formatting strings i.e. "%s $" in description files to match prefix/suffix requirements.

**Comment by mjrouser** [comment]
I think you're right.  I changed the formatting for the new page, but then
realized it threw off the formatting for other values.  Seems we'll need a
if/than or filter function to sort first and then format.




---
http://mjrouser.com
