### ISSUE TITLE
Validate links between menu and displayed data

### ISSUE THREAD

**Issue by bouviervj** [codeforboston/ungentry#90]
When testing menu, by clicking on a property, it seems that the new data is not pushed to the map. We should verify that all fields are correctly mapped between the menu and map properties.

**Comment by mjrouser** [comment]
I'll work on this now.  I need to edit the ```variables.js``` file

**Comment by mjrouser** [comment]
I manually mapped the variables to the menu and it should clear up everything until we can fix the inconsistencies in the csv.
