### ISSUE TITLE
Feature: Select Census Tracts in Mobile View

### ISSUE THREAD

**Issue by donmccurdy** [codeforboston/ungentry#94]
Hey, I was thinking a bit about how selecting tracts might work on mobile, and had a couple ideas and some experimental code for each.

### Single Selection

If viewing details for a single tract (like what is currently on desktop) is probably the best interaction right now, that should be pretty easy to add:

1. User taps a census tract.
2. Tract is selected/highlighted.
3. Footer toggle button bounces/glows/flashes for a second, letting you know it has new content.

![n7tfy](https://cloud.githubusercontent.com/assets/1848368/8273613/9d5f08ea-1843-11e5-8511-ab3b2c3234b8.gif)

### Multiple Selection

The other way I could see this going would be to let users select multiple tracts, without needing to open/close the modal each time, and have those selected tracks show up in a table or graph once the footer is opened:

![screen shot 2015-06-21 at 6 47 48 pm](https://cloud.githubusercontent.com/assets/1848368/8273694/18c9eaf2-1846-11e5-9c06-581b20d74c16.png)

![table-01](https://cloud.githubusercontent.com/assets/1848368/8273710/79cb6e48-1846-11e5-8fe5-0d328d9586a9.jpg)

That doesn't sound like _too_ much more work, maybe using a separate instances of subSelect.js? But definitely more work than single-select. Mostly a matter of whether it's useful or worth the time right now.

**Comment by mjrouser** [comment]
@donmccurdy Thanks for the great illustrations!  I think the single tract select would be a great place to start.  I like the idea stylistically of putting the data in a table.  It could help provide a good hierarchy for the iWindow.

**Comment by donmccurdy** [comment]
Sounds good. I'm working on a PR for subSelect.js right now that should handle the single-select case while leaving some room open for multi-select later.
